server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful

spring:
  task:
    scheduling:
      pool:
        size: 8  # ??? 8??? ?? ??

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


firebase:
  config:
    path: firebase-resources/firebase-service-account.json

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger